blank_issues_enabled: false
contact_links:
  - name: Questions or Help
    url: https://sciwiki.fredhutch.org/datascience/wilds_docker/
    about: For questions, check our documentation or email us at wilds@fredhutch.org
